import './globals.css'
import { Inter } from 'next/font/google'
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{background:'#ededed'}}>
      <ToastContainer />

        {/* <h1>side menu</h1> */}
        {children}
        {/* <h1>footer </h1> */}
        </body>
    </html>
  )
}
